-- Supprimer les relations
DROP TABLE IF EXISTS VALIDE;
DROP TABLE IF EXISTS PARTICIPE;
DROP TABLE IF EXISTS IMPLIQUE;
DROP TABLE IF EXISTS POSSEDE;   
DROP TABLE IF EXISTS REQUIERT;  

-- Supprimer les entités dépendantes
DROP TABLE IF EXISTS ECHANTILLON;
DROP TABLE IF EXISTS MAINTENANCE;
DROP TABLE IF EXISTS CAMPAGNE;

-- Supprimer les tables principales
DROP TABLE IF EXISTS BUDGET;
DROP TABLE IF EXISTS PERSONNEL;
DROP TABLE IF EXISTS PLATEFORME;
DROP TABLE IF EXISTS HABILITATION; 